name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip ccache libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install "cython<3.0.0" "setuptools<70.0.0" buildozer

      # --- ДОБАВЬ ЭТОТ ШАГ ---
      - name: Install AIDL and Build Tools
        run: |
          sudo apt-get install -y android-sdk-platform-tools
          # Подтягиваем build-tools с помощью sdkmanager
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.2" "platforms;android-33"
          # Делаем симлинк, чтобы buildozer точно увидел aidl в PATH
          sudo ln -sf $ANDROID_HOME/build-tools/33.0.2/aidl /usr/local/bin/aidl
      # ------------------------

      - name: Build with Buildozer
        run: |
          buildozer --allow-root -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
